select
    event_id,
    magnitude,
    place,
    event_time,
    updated_time,
    tz as time_zone_offset,
    felt as felt_reports,
    cdi as community_intensity,
    mmi as mercalli_intensity,
    alert as alert_level,
    status as event_status,
    tsunami as tsunami_flag,
    significance as significance_score,
    network as source_network,
    code as network_event_code,
    ids as associated_ids,
    sources as id_sources,
    types as available_data_types,
    nst as station_count,
    dmin as nearest_station_distance,
    rms as rms_residual,
    gap as azimuthal_gap,
    magnitude_type,
    event_type,
    title as event_title,
    longitude,
    latitude,
    depth,
    country,
    region,
    year as event_year,
    month as event_month,
    day as event_day,
    hour as event_hour

from {{ source('earthquake', 'earthquakes') }}