earthquake_dbt:
  outputs:
    dev:
      dbname: earthquake
      host: postgres
      pass: admin
      port: 5432
      schema: earthquake
      threads: 4
      type: postgres
      user: admin
  target: dev
