{
  "type": "record",
  "name": "Earthquake",
  "namespace": "earthquake",
  "fields": [
    {"name": "event_id", "type": "string"},
    {"name": "magnitude", "type": ["null", "double"], "default": null},
    {"name": "place", "type": ["null", "string"], "default": null},
    {"name": "event_time", "type": "long"},
    {"name": "updated_time", "type": "long"},
    {"name": "tz", "type": ["null", "int"], "default": null},
    {"name": "felt", "type": ["null", "int"], "default": null},
    {"name": "cdi", "type": ["null", "double"], "default": null},
    {"name": "mmi", "type": ["null", "double"], "default": null},
    {"name": "alert", "type": ["null", "string"], "default": null},
    {"name": "status", "type": ["null", "string"], "default": null},
    {"name": "tsunami", "type": "int"},
    {"name": "significance", "type": "int"},
    {"name": "network", "type": ["null", "string"], "default": null},
    {"name": "code", "type": ["null", "string"], "default": null},
    {"name": "ids", "type": ["null", "string"], "default": null},
    {"name": "sources", "type": ["null", "string"], "default": null},
    {"name": "types", "type": ["null", "string"], "default": null},
    {"name": "nst", "type": ["null", "int"], "default": null},
    {"name": "dmin", "type": ["null", "double"], "default": null},
    {"name": "rms", "type": ["null", "double"], "default": null},
    {"name": "gap", "type": ["null", "double"], "default": null},
    {"name": "magnitude_type", "type": ["null", "string"], "default": null},
    {"name": "event_type", "type": ["null", "string"], "default": null},
    {"name": "title", "type": ["null", "string"], "default": null},
    {"name": "longitude", "type": "double"},
    {"name": "latitude", "type": "double"},
    {"name": "depth", "type": "double"}
  ]
}