CREATE SCHEMA IF NOT EXISTS earthquake;

CREATE TABLE IF NOT EXISTS earthquake.earthquakes (
    event_id VARCHAR(50) PRIMARY KEY,
    magnitude DOUBLE PRECISION,
    place TEXT,
    event_time TIMESTAMP NOT NULL,
    updated_time TIMESTAMP NOT NULL,
    tz INTEGER,
    felt INTEGER,
    cdi DOUBLE PRECISION,
    mmi DOUBLE PRECISION,
    alert VARCHAR(20),
    status VARCHAR(20),
    tsunami INTEGER NOT NULL,
    significance INTEGER NOT NULL,
    network VARCHAR(20),
    code VARCHAR(50),
    ids TEXT,
    sources TEXT,
    types TEXT,
    nst INTEGER,
    dmin DOUBLE PRECISION,
    rms DOUBLE PRECISION,
    gap DOUBLE PRECISION,
    magnitude_type VARCHAR(20),
    event_type VARCHAR(50),
    title TEXT,
    longitude DOUBLE PRECISION NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    depth DOUBLE PRECISION NOT NULL,
    year INTEGER NOT NULL,
    month INTEGER NOT NULL,
    day INTEGER NOT NULL,
    hour INTEGER NOT NULL
);